const avatarIconNames = [
    "fa-solid fa-person",
    "fa-solid fa-person-dress",
    "fa-solid fa-person-walking-luggage",
    "fa-solid fa-person-running",
    "fa-solid fa-person-skiing",
    "fa-solid fa-person-hiking",
    "fa-solid fa-person-falling",
    "fa-solid fa-person-digging",
    "fa-solid fa-square-person-confined",
    "fa-solid fa-baby",
    "fa-solid fa-user-secret",
    "fa-solid fa-person-breastfeeding",
    "fa-solid fa-person-biking",
    "fa-solid fa-user-graduate",
    "fa-solid fa-user-ninja",
    "fa-solid fa-person-cane",
    "fa-solid fa-user-doctor",
    "fa-solid fa-user-tie",
    "fa-solid fa-user-astronaut",
    "fa-solid fa-house-chimney-user",
    "fa-solid fa-child-dress",
    "fa-solid fa-bed",
    "fa-solid fa-person-swimming",
]

const cartIconNames = [
    "fa-solid fa-cart-shopping",
    "fa-solid fa-cart-flatbed",
    "fa-solid fa-dolly",
    "fa-solid fa-truck-arrow-right",
    "fa-solid fa-truck",
    "fa-solid fa-truck-fast",
    "fa-solid fa-cart-arrow-down",
    "fa-solid fa-cart-plus",
    "fa-solid fa-basket-shopping",
    "fa-solid fa-bag-shopping",
    "fa-brands fa-shopify",
]

const products = [
    {name: 'small combination',color: 'dodgerblue', price: '9.99sheq',
    icon: "fa-solid fa-sack-dollar",isSale:true, 
     contains:[{what:'apple',icon:'fa-apple-whole',color:'green'},
            {what:'apple',icon:'fa-apple-whole',color:'red'},
            {what:'apple',icon:'fa-apple-whole',color:'yellow'}]},
    {name: 'small set',color: 'red', price: '39.99sheq',
    icon: "fa-solid fa-sack-dollar",stars:2,
     contains:[{what:'wine',icon:'fa-wine-bottle',color:'red'},
            {what:'apple',icon:'fa-apple-whole',color:'red'},
            {what:'hot-pepper',icon:'fa-pepper-hot',color:'red'}]},
    {name: 'small set',color: 'lightseagreen', price:'14.99sheq',
    icon: "fa-solid fa-sack-dollar",isSale: true,stars:4,
     contains:[{what:'green',icon:'fa-seedling',color:'green'},
            {what:'apple',icon:'fa-apple-whole',color:'green'},
            {what:'hot-pepper',icon:'fa-pepper-hot',color:'green'}]},
    {name: 'small set',color: 'green', price: '20.99sheq',
    icon: "fa-solid fa-sack-dollar", stars: 5,
     contains:[{what:'green',icon:'fa-seedling',color:'green'},
            {what:'apple',icon:'fa-apple-whole',color:'green'},
            {what:'hot-pepper',icon:'fa-pepper-hot',color:'green'}]},
    {name: 'medium combination',color: 'greenyellow', price: '59.99sheq',
    icon: "fa-solid fa-gift",
    contains:[[{what:'apple',icon:'fa-apple-whole',color:'green'},
                {what:'apple',icon:'fa-apple-whole',color:'green'},
                {what:'apple',icon:'fa-apple-whole',color:'green'}],
            {what:'apple',icon:'fa-apple-whole',color:'red'},
            [{what:'apple',icon:'fa-apple-whole',color:'yellow'},
            {what:'apple',icon:'fa-apple-whole',color:'yellow'}]]},
    {name: 'medium set',color: 'red', price: '109.99sheq',
      icon: "fa-solid fa-gift",
    contains:[[{what:'wine',icon:'fa-wine-bottle',color:'red'},
                {what:'wine',icon:'fa-wine-bottle',color:'red'},
                {what:'wine',icon:'fa-wine-bottle',color:'pink'},
                {what:'wine',icon:'fa-wine-bottle',color:'pink'}],
            [{what:'apple',icon:'fa-apple-whole',color:'red'},
            {what:'apple',icon:'fa-apple-whole',color:'red'}],
            {what:'raspberry',icon:'fa-raspberry-pi',color:'red'},
            {what:'apple',icon:'fa-apple-whole',color:'red'},
            {what:'hot-pepper',icon:'fa-pepper-hot',color:'red'}]}, 
                  
    {name: 'large combination',color: 'purple', price: '209.99sheq',
    icon:"fa-solid fa-boxes-packing",
    contains:[[{what:'wine',icon:'fa-wine-bottle',color:'red'},
                {what:'wine',icon:'fa-wine-bottle',color:'red'},
                {what:'wine',icon:'fa-wine-bottle',color:'pink'},
                {what:'wine',icon:'fa-wine-bottle',color:'pink'},
                [{what:'wine',icon:'fa-wine-glass',color:'cornflowerblue'},
                {what:'wine',icon:'fa-wine-glass',color:'cornflowerblue'},
                {what:'wine',icon:'fa-wine-glass',color:'cornflowerblue'},
                {what:'wine',icon:'fa-wine-glass',color:'violet'},
                {what:'wine',icon:'fa-wine-glass',color:'violet'}],
                [{what:'wine',icon:'fa-martini-glass',color:'pink'},
                {what:'wine',icon:'fa-martini-glass',color:'orange'},
                {what:'wine',icon:'fa-martini-glass',color:'pink'},
                {what:'wine',icon:'fa-martini-glass',color:'orange'},
                {what:'wine',icon:'fa-martini-glass',color:'orange'}]
                
            ],
            [{what:'apple',icon:'fa-apple-whole',color:'red'},
            {what:'apple',icon:'fa-apple-whole',color:'red'}],
            [{what:'raspberry',icon:'fa-raspberry-pi',color:'purple'},
            {what:'raspberry',icon:'fa-raspberry-pi',color:'purple'},
            {what:'raspberry',icon:'fa-raspberry-pi',color:'red'},
            {what:'raspberry',icon:'fa-raspberry-pi',color:'red'}],
            {what:'apple',icon:'fa-apple-whole',color:'red'},
            {what:'hot-pepper',icon:'fa-pepper-hot',color:'red'}]},        
            
            
]